### ISSUE TITLE
Excessive memory consumption with real world data

### ISSUE THREAD

**Issue by filestuff** [aresPanos/dmgp_dfgp_regression#1]
I tried running the real world examples provided (protein and elevators) but both failed due to exhaustion of memory. I ran the code on a Google AI notebook with 16 vCPUs and 128GB RAM. Monitoring also confirmed all memory was consumed. Is there a problem with the code? or is this a problem on my side? I ran the the code as is with the requirement versions as specified.

**Comment by aresPanos** [comment]
The code has been tested successfully in cases where the user runs the scripts directly as "python3 <script_name>.py". There were no memory management issues during tests where a 8Gb RAM local machine was used. I do not see why notebook creates this memory leakage problems.

**Comment by filestuff** [comment]
The problem appears to be in specifying the flags.

Not sure exactly the cause but:
`python src/main_realData.py --dataset=protein --batch_size=1000 --display_freq=10 --num_splits=5 --m_dmgp=15 --d_dmgp=1  --m_dfgp=20 --d_dmgp=4 --use_dnn_init=True`
causes a memory leak and:
`python src/main_realData.py`
works as expected.

Thank you for the quick reply earlier.

**Comment by aresPanos** [comment]
Based on your example above, the problem arises from the fact you use m_dmgp=15 and d_dmgp=4 (actually d_dmgp has been defined twice in your example; you need to specify d_dfgp instead). 
By using these parameters, you ask the algorithm to use a "low"-rank approximation for the covariance matrix with rank= m_dmgp ** d_dmgp  = 50625, i. e. you need to store matrices (with double values) of size  50625 x 50625 which is massive, hence the memory exhaustion problem. Otherwise, the code should run with no further issues.
